version: '3'

vars:
  TARGET: prezto
  DESC: "PREZTO CONFIG"

includes:
  deps:
    dir: ../deps
    taskfile: ../deps/Taskfile.yaml

tasks:
  default:
    cmds:
      - task: setup-deps
      - task: download
      - task: mkpkg

  setup-deps:
    cmds:
      - task: deps:makeself

  mkpkg:
    silent: true
    cmds:
      - cp Taskfile.setup.yaml data/Taskfile.yaml
      - cp ../deps/helper.sh data/helper.sh
      - ../deps/makeself.sh data {{.TARGET}}.run "{{.DESC}}" ./helper.sh > /dev/null
    sources:
      - Taskfile.setup.yaml
      - ../deps/helper.sh
    status:
      - test -f data/Taskfile.yaml
      - test -f {{.TARGET}}.run

  cleanup:
    cmds:
      - rm -rf data {{.TARGET}}.run

  download:
    cmds:
      - git clone -q --recursive https://github.com/sorin-ionescu/prezto.git data/prezto
      - cd data/prezto/modules/history-substring-search/external && git checkout -q master
      - curl -sSL https://raw.githubusercontent.com/mritd/init/master/prezto/zshrc -o data/prezto/runcoms/zshrc
      - curl -sSL https://raw.githubusercontent.com/mritd/init/master/prezto/zpreztorc -o data/prezto/runcoms/zpreztorc
      - curl -sSL https://raw.githubusercontent.com/docker/cli/master/contrib/completion/zsh/_docker -o data/prezto/modules/completion/external/src/_docker
    status:
      - test -f data/prezto/runcoms/zshrc
      - test -f data/prezto/runcoms/zpreztorc
      - test -f data/prezto/modules/completion/external/src/_docker
