name: docker-images

on:
  workflow_dispatch:
    inputs:
      images:
        description: 'Download Docker Images'
        required: true

env:
  S3_PREFIX: ${{ secrets.S3_PREFIX }}
  S3_ADDRESS: ${{ secrets.S3_ADDRESS }}
  S3_ACCESSKEY: ${{ secrets.S3_ACCESSKEY }}
  S3_SECRETKEY: ${{ secrets.S3_SECRETKEY }}
  NOTI_TOKEN: ${{ secrets.NOTI_TOKEN }}
  NOTI_ADDRESS: ${{ secrets.NOTI_ADDRESS }}
  DOCKER_IMAGES: ${{ github.event.inputs.images }}
  TARBALL_NAME: docker_images.${{ github.run_id }}.tar
  FORCE_COLOR: 1

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: Install minio/mc
      run: |
        curl -sSL https://dl.min.io/client/mc/release/linux-amd64/mc > /usr/local/bin/mc
        chmod +x /usr/local/bin/mc
        mc alias set genx ${S3_ADDRESS} ${S3_ACCESSKEY} ${S3_SECRETKEY}
    - name: Download
      run: |
        mkdir sync && cd sync
        OLD_IFS="${IFS}"
        IFS=","
        images=(${DOCKER_IMAGES})
        IFS="${OLD_IFS}"
        for img in ${images[@]}; do
          docker pull ${img}
        done
        docker save $(echo ${DOCKER_IMAGES} | sed 's@,@ @g') > ${TARBALL_NAME}
    - name: Upload to S3
      run: mc cp sync/* genx/shared/temp
    - name: Notification
      run: |
        curl -X POST -H "X-Auth: ${NOTI_TOKEN}" ${NOTI_ADDRESS} \
          -d message="Docker Images: \`${S3_PREFIX}/${TARBALL_NAME}\`&markdown=true"
