name: go-task

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Manually trigger'
        required: true

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      S3_ADDRESS: ${{ secrets.S3_ADDRESS }}
      S3_ACCESSKEY: ${{ secrets.S3_ACCESSKEY }}
      S3_SECRETKEY: ${{ secrets.S3_SECRETKEY }}
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: Dwonload go-task 
      run: bash deps/download-task.sh
    - name: Download mc
      run: |
        curl -sSL https://dl.min.io/client/mc/release/linux-amd64/mc > /usr/local/bin/mc
        chmod +x /usr/local/bin/mc
        mc alias set genx ${S3_ADDRESS} ${S3_ACCESSKEY} ${S3_SECRETKEY}
    - name: Upload to S3
      run: mc cp dist/*.tar.gz genx/shared/go-task
