name: sync

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Download URL'
        required: true

env:
  S3_PREFIX: ${{ secrets.S3_PREFIX }}
  S3_ADDRESS: ${{ secrets.S3_ADDRESS }}
  S3_ACCESSKEY: ${{ secrets.S3_ACCESSKEY }}
  S3_SECRETKEY: ${{ secrets.S3_SECRETKEY }}
  NOTI_TOKEN: ${{ secrets.NOTI_TOKEN }}
  NOTI_ADDRESS: ${{ secrets.NOTI_ADDRESS }}
  DOWNLOAD_URL: ${{ github.event.inputs.url }}
  FORCE_COLOR: 1

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Task
      uses: arduino/setup-task@v1
    - name: Install minio/mc
      run: |
        curl -sSL https://dl.min.io/client/mc/release/linux-amd64/mc > /usr/local/bin/mc
        chmod +x /usr/local/bin/mc
        mc alias set genx ${S3_ADDRESS} ${S3_ACCESSKEY} ${S3_SECRETKEY}
    - name: Download
      run: |
        mkdir sync && cd sync
        wget ${DOWNLOAD_URL}
    - name: Upload to S3
      run: mc cp sync/* genx/shared/temp
    - name: Notification
      run: |
        curl -X POST -H "X-Auth: ${NOTI_TOKEN}" ${NOTI_ADDRESS} \
          -d message="\`${S3_PREFIX}/$(basename ${DOWNLOAD_URL})\`&markdown=true"
